# Generated by Django 3.1.3 on 2020-11-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkweather', '0002_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, default='kathmandu'),
            preserve_default=False,
        ),
    ]
